- name: PLAY1
  hosta: local
  connection: local
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
      msg: "hello world from play1 task1"
  - name: play2 and task2
    ansible.builtin.debug:
      msg: "hellow world from play2 and task2"    